config-version: 2

aliases:
  world:
  - survival

groups:
  world:
  - world_nether

options:
  pvp:
    delay: 30
    attack-cancel: true
    damage-cancel: true

blacklist:
- creative
- pvp

debug: false
