name: Excursion
version: 0.1
description: A teleport plugin that remembers your previous location in the world.
author: ZerothAngel
main: org.tyrannyofheaven.bukkit.Excursion.ExcursionPlugin
database: true
commands:
  visit:
    description: Visit the specified world
    permission: excursion.visit
    usage: /<command> [world]
permissions:
  excursion.visit:
    description: Allows use of the /visit command
    default: op
  excursion.access.*:
    description: Allows access to all worlds
    default: op
